### ISSUE TITLE
Crash when app goes to background

### ISSUE THREAD

**Issue by egidijus-kuzma** [Kennyc1012/BottomSheetMenu#71]
Steps to reproduce:
1. Bottom sheet visible
2. App goes to background ( In developer options option "Don't keep activities" checked)
3. App restored from background - crash   

```
 Process: com.demo.android, PID: 31505
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demo.android/com.demo.android.MainActivity}: android.view.InflateException: Binary XML file line #23 in com.demo.android:layout/activity_main: Binary XML file line #20 in com.demo.android:layout/content_main: Error inflating class fragment
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3640)
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3797)
    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at android.os.Looper.loopOnce(Looper.java:346)
    	at android.os.Looper.loop(Looper.java:475)
    	at android.app.ActivityThread.main(ActivityThread.java:7890)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
    Caused by: android.view.InflateException: Binary XML file line #23 in com.demo.android:layout/activity_main: Binary XML file line #20 in com.demo.android:layout/content_main: Error inflating class fragment
    Caused by: android.view.InflateException: Binary XML file line #20 in com.demo.android:layout/content_main: Error inflating class fragment
    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property builder has not been initialized
    	at com.kennyc.bottomsheet.BottomSheetMenuDialogFragment.onCreateDialog(BottomSheetMenuDialogFragment.kt:287)
    	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:665)
    	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:579)
    	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1752)
    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
    	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
    	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
    	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
 E  	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
    	at com.demo.android.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:50)
    	at com.demo.android.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:44)
    	at com.demo.android.MainActivity.onCreate(MainActi
```vity.kt:25)

**Comment by egidijus-kuzma** [comment]
Thanks :)
